version: '3.9'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.1
    deploy:
      replicas: 1
    ports:
     - "9200:9200"
    tty: true    
    environment:
     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
     - "discovery.type=single-node"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.1
    deploy:
      replicas: 1
    ports:
     - "5601:5601"
    depends_on:
      - elasticsearch
    tty: true
    environment:
      - ELASTICSEARCH.HOSTS=http://elasticsearch:9200
