version: '3.9'
services:

  redis:
    image: redis:latest
    deploy:
      replicas: 1
    ports:
     - "6379:6379"
    tty: true
    volumes:
      - redis-volume:/data

volumes:
  redis-volume:
    external: true