version: "3.9"
services:
  mssql:
    image: mcr.microsoft.com/mssql/server
    deploy:
      replicas: 1
    ports:
      - "1433:1433"
    tty: true
    environment:
      - "ACCEPT_EULA=Y"
      - "MSSQL_PID=Standard"
      - "SA_PASSWORD=yourStrong(!)Password"
      - "MSSQL_AGENT_ENABLED=true"
    volumes:
      - mssql-volume:/var/opt/mssql

volumes:
  mssql-volume:
    external: true
