version: '3.9'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.1
    deploy:
      replicas: 1
    ports:
     - "9200:9200"
    tty: true    
    environment:
     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
     - "discovery.type=single-node"